import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { queueCalendar,queueNotification } from "@/lib/notifications";
import { error,ok } from "@/lib/http";
import { calculateReminderTier } from "@/lib/reminders";
import { lockDoctorSlot } from "@/lib/slot-lock";
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){try{const u=await requireUser("PATIENT");const {id}=await params;const reminderTier = await calculateReminderTier(u.id);
const a=await prisma.$transaction(async tx=>{const row=await tx.appointment.findUnique({where:{id},include:{doctor:{include:{user:true}},patient:true}});if(!row||row.patientId!==u.id)throw new Error("NOT_FOUND");if(row.status!=="PENDING")throw new Error("INVALID_STATUS");if(row.holdExpiresAt&&row.holdExpiresAt<new Date())throw new Error("HOLD_EXPIRED");await lockDoctorSlot(tx,row.doctorId,row.startTime);const conflicts=await tx.appointment.findMany({where:{doctorId:row.doctorId,id:{not:id},status:"CONFIRMED",startTime:{lt:row.endTime},endTime:{gt:row.startTime}}});if(conflicts.length)throw new Error("SLOT_UNAVAILABLE");const updated=await tx.appointment.update({where:{id},data:{status:"CONFIRMED",holdExpiresAt:null,reminderTier}});await tx.notification.createMany({data:[{userId:row.patientId,appointmentId:id,type:"BOOKING_CONFIRMATION",subject:"Appointment confirmed",body:`Your appointment with ${row.doctor.user.name} is confirmed for ${row.startTime.toLocaleString()}.`},{userId:row.doctor.userId,appointmentId:id,type:"BOOKING_CONFIRMATION",subject:"New appointment booked",body:`${row.patient.name} booked an appointment for ${row.startTime.toLocaleString()}.`}]});await tx.calendarEvent.createMany({data:[{userId:row.patientId,appointmentId:id,operation:"CREATE"},{userId:row.doctor.userId,appointmentId:id,operation:"CREATE"}]});return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return ok({appointment:a});}catch(e){const m=e instanceof Error?e.message:"";if(m==="HOLD_EXPIRED")return error("Your slot hold expired. Please select the slot again",409);if(m==="SLOT_UNAVAILABLE")return error("That slot is no longer available",409);if(m==="NOT_FOUND")return error("Appointment not found",404);return error("Could not confirm appointment",400);}}
